[package]
name = "blackboard"
version = "1.0.0"
authors = ["mocoma <mocomaminecraft@gmail.com>"]
edition = "2018"

description = "A simple blackboard design pattern implementation in rust"
license = "MIT"
repository = "https://github.com/mocomaminecraft/blackboard"

[dependencies]
